export const toolActions = [
  {
    id: 'slack',
    tool: 'Slack',
    functions: [
      { name: 'Post Channel Message', time: '1 min' },
      { name: 'Create Announcement', time: '2 min' },
      { name: 'Fetch Recent Messages', time: '1 min' },
      { name: 'Invite User to Channel', time: '1.5 min' },
    ],
    time: '3 min',
    iconPath: '/textures/Slack.png',
    color: '#000000',
  },
  {
    id: 'gmail',
    tool: 'Gmail',
    functions: [
      { name: 'Send Email', time: '2 min' },
      { name: 'Draft Reply', time: '1.5 min' },
      { name: 'Search Inbox', time: '1 min' },
      { name: 'Label or Archive Message', time: '0.5 min' },
    ],
    time: '2 min',
    iconPath: '/textures/Gmail.png',
    color: '#000000',
  },
  {
    id: 'gdrive',
    tool: 'Google Drive',
    functions: [
      { name: 'Upload File', time: '1.5 min' },
      { name: 'Search for Document', time: '1 min' },
      { name: 'Share File with User', time: '1.5 min' },
      { name: 'List Files in Folder', time: '0.5 min' },
    ],
    time: '1.5 min',
    iconPath: '/textures/Google Drive.png',
    color: '#000000',
  },
  {
    id: 'notion',
    tool: 'Notion',
    functions: [
      { name: 'Create New Page', time: '1 min' },
      { name: 'Update Database Entry', time: '1.5 min' },
      { name: 'Query Tasks by Status', time: '1 min' },
      { name: 'Add Comment to Page', time: '0.5 min' },
    ],
    time: '1 min',
    iconPath: '/textures/Notion.png',
    color: '#000000',
  },
  {
    id: 'linear',
    tool: 'Linear',
    functions: [
      { name: 'Create Issue', time: '1.5 min' },
      { name: 'Update Ticket Status', time: '1 min' },
      { name: 'Assign Issue to Teammate', time: '1 min' },
      { name: 'List Open Issues', time: '0.5 min' },
    ],
    time: '2.5 min',
    iconPath: '/textures/Linear.png',
    color: '#000000',
  },
  {
    id: 'gsheets',
    tool: 'Google Sheets',
    functions: [
      { name: 'Append Row', time: '1 min' },
      { name: 'Update Cell Range', time: '1.5 min' },
      { name: 'Read Spreadsheet Data', time: '1 min' },
      { name: 'Create New Sheet', time: '1.5 min' },
    ],
    time: '3 min',
    iconPath: '/textures/Google Sheets.png',
    color: '#000000',
  },
  {
    id: 'reddit',
    tool: 'Reddit',
    functions: [
      { name: 'Fetch Top Posts', time: '1 min' },
      { name: 'Comment on Thread', time: '1.5 min' },
      { name: 'Upvote Post', time: '0.5 min' },
      { name: 'Submit New Post', time: '2 min' },
    ],
    time: '2 min',
    iconPath: '/textures/Reddit.png',
    color: '#000000',
  },
  {
    id: 'trello',
    tool: 'Trello',
    functions: [
      { name: 'Create Card', time: '1.5 min' },
      { name: 'Move Card Between Lists', time: '1 min' },
      { name: 'Add Comment to Card', time: '0.5 min' },
      { name: 'List Cards on Board', time: '1 min' },
    ],
    time: '2.5 min',
    iconPath: '/textures/Trello.png',
    color: '#000000',
  },
  {
    id: 'figma',
    tool: 'Figma',
    functions: [
      { name: 'List Frames in File', time: '1 min' },
      { name: 'Fetch Comments', time: '1 min' },
      { name: 'Get Component Metadata', time: '1.5 min' },
      { name: 'Render Design Thumbnail', time: '2 min' },
    ],
    time: '3 min',
    iconPath: '/textures/Figma.png',
    color: '#000000',
  },
  {
    id: 'gsearch',
    tool: 'Google',
    functions: [
      { name: 'Search Query', time: '1 min' },
      { name: 'Get Top Result Summary', time: '1.5 min' },
      { name: 'Find Related Articles', time: '2 min' },
      { name: 'Extract URLs from Results', time: '1 min' },
    ],
    time: '2 min',
    iconPath: '/textures/Google.png',
    color: '#000000',
  },
  {
    id: 'github',
    tool: 'GitHub',
    functions: [
      { name: 'Create Issue', time: '1.5 min' },
      { name: 'List Pull Requests', time: '1 min' },
      { name: 'Comment on PR', time: '1 min' },
      { name: 'Fetch Repository Info', time: '1 min' },
    ],
    time: '2.5 min',
    iconPath: '/textures/Github.png',
    color: '#000000',
  },
]


